version: "2"
services:

  apigateway:
    #image: zuul-service
    build: springgatewayapi/
    restart: always
    network_mode: host
    depends_on:
      - eurekaserver
    ports:
      - 8096:8096
    expose:
      - 8096

  eurekaserver:
    #image: eureka-servcie:latest
    build: spring-eureka-server/
    restart: always
    network_mode: host
    ports:
      - 8761:8761
    expose:
      - 8761

  configserver:
    build: spring-config-server/
    restart: always
    network_mode: host
    ports:
      - 8888:8888
    expose:
      - 8888

  musicservice:
    build: muzix-service/
    restart: always
    network_mode: host
    depends_on:
      - eurekaserver
      - configserver
      - apigateway
    ports:
      - 8071:8071
    expose:
      - 8071

  userservice:
    build: user-service/
    restart: always
    network_mode: host
    depends_on:
      - eurekaserver
      - configserver
      - apigateway
    ports:
      - 8090:8090
    expose:
      - 8090

  mongodb:
    image: mongo:3.4-xenial
    restart: always
    network_mode: host
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - ./data:/data/db